### ISSUE TITLE
Can't clear out everything.

### ISSUE THREAD

**Issue by norrisgc** [jfchapman/VUPlayer#3]
This may be by design, but I can't clear out everything (or indeed *anything*) which has been added to version 4. "Remove track(s)" is always greyed out.

**Comment by jfchapman** [comment]
Version 4 works slightly differently to older versions, in that it maintains a database of all media files. This is so it can build up a tree of artists, albums, etc, and also means that adding tracks to a playlist is quick, if there is an existing database entry.
When you delete a track from a playlist (or favourites), it just removes the track from the playlist, but not from the database, so the track will still remain in All Tracks, Albums, Genres, etc.
I'll have a think about allowing tracks to be deleted from All Tracks, Albums, etc. This would mean removing the database entry & removing the track from all playlists.

**Comment by iamjaydear** [comment]
Referring to the now closed issue I raised (Removing tracks #2)... Playlists are OK, I can see the benefits, but I've since found that double-clicking an m3u playlist when VUPlayer has been made the default application does NOT open the playlist in VUP, so there's no convenience there, quite the opposite! I've had to revert to a different player, because all I want to do most of the time is to quickly check mp3's I've made. I really love a lot of what you've put in VUP, especially the VU's but the playlist thing needs streamlining and I'd suggest that simply opening and closing mp3s (or whatever format) needs to be **much** easier. I don't think I need a mega-list of everything I've ever played, but I could be wrong - time will tell.

**Comment by jfchapman** [comment]
There is some missing functionality with regards to opening tracks/playlists from the command line/shell, so that will be why m3u playlists don't open correctly. It's on the list of things which are missing compared to the old versions. The work in progress currently looks like this:
- CD audio support (playback/ripping/Gracenote)
- Graphic equalizer
- Playback queue (play next, add to queue, etc).
The playback queue will essentially be the currently playing playlist and will hopefully deal with most of the issues mentioned above.

**Comment by norrisgc** [comment]
I think I'll be continuing to use the old VUPlayer for as long as it still works. I have my music organized outside of any player, and don't find much, if any, benefit from having things organize them any differently. I organize by artist, but automated organization by artist often seems to produce rather useless results - the same artist showing up more than once (e.g. spelled slightly differently,) or things listed under a minor collaborator. Then there's the overhead of doing all the scanning and storing results - and the need to keep refreshing it, which may result in things moving.

So, I appreciate the effort, but V4's just not for me.

**Comment by jfchapman** [comment]
It's now possible to remove tracks from the media library (e.g. not just playlists) as of v4.3.
