### ISSUE TITLE
How to show which track is playing

### ISSUE THREAD

**Issue by rocky1913** [jfchapman/VUPlayer#38]
When I start playing the first track on a list of several to play, the track is highlighted.  However, when play continues to the next track on the list, the first track remains highlighted, not the track currently playing.  In my older version of VUPlayer, I could tell at a glance which track I was hearing because that track on the list was always highlighted.   I can't find a setting that would make this happen.

**Comment by jfchapman** [comment]
Hi,

Yes, for the next version, I am hoping to add an option to use the old VUPlayer behaviour of 'following' the current selection during playback (and selecting the currently playing track in the list).

Thanks,
James

**Comment by rocky1913** [comment]
Great!  Thanks for letting me know.

Stephen

**Comment by jfchapman** [comment]
Hi,

The latest 4.18 release now has a 'Follow Track Selection' playback mode, which mimics the behaviour of legacy application versions. Specifically (from the wiki), when reaching the end of the currently playing track:

- If the currently playing track is selected, playback will continue with the next track in the playlist, and the next track will be selected.
- If the currently playing track is not selected, playback will continue with the next selected track in the currently displayed playlist.
- If no tracks are selected, playback will stop.

This is about as close as I could get to the old behaviour, bearing in mind the legacy application versions only supported a single playlist. This mode could also be used to queue up the next track from another playlist, so that might prove useful in some cases. 

Thanks,
James

**Comment by rocky1913** [comment]
Thank you so much! I’ve tried it, and it does exactly what I need.  What a nice Christmas present!

Stephen Peithman
