### ISSUE TITLE
Add support .cue?

### ISSUE THREAD

**Issue by amadicus** [jfchapman/VUPlayer#41]
Hello.  Is it possible to add support for .cue files?  My music collection mainly consists of disk images.  When added to the player, there is one file in the playlist.  I wish there was a breakdown into tracks.  Thank you.

**Comment by amadicus** [comment]
A small clarification.  When you open Explorer and select a folder, the image file opens - not by track.  When adding a folder to a playlist, it is split into tracks, but the whole file is also added (i.e. a disk image is added + split into tracks, duplicated)

**Comment by jfchapman** [comment]
Hi,

Yes, the support for cue files was only added in the last version, so there might be a few issues with it. I don't use cue files myself, so I've only done limited testing. 

The folder browser only loads music files, not playlist files, so you'll only see the 'backing' audio file as one entry, not split up into individual tracks.

Import playlist, add files (if you select cue files), and dragging and dropping a cue file into the main playlist window should import the playlist OK into the separate tracks, without adding the backing audio file. 
Add folder (or dropping a folder into the main playlist window) will add all audio files and playlists in that folder, so for cue files, you'll get the individual tracks as well as the backing track. This is probably going to be a problem with all folders with a mixture of playlists and audio files, so I'll take a look at it, and try and find a good way of filtering out duplicates.

Thanks,
James

**Comment by jfchapman** [comment]
Hi,

It's a bit overdue, but the latest version of the application (v4.19) has some changes in the way cue sheets are handled.
In the folder browser, cue sheets are now recognised, so the playlist should now display the correct cue points, instead of just adding the files. Also, when adding a folder to a playlist, if there are any cue files in the folder it should add just the cue points and not the actual files.

Thanks,
James
