### ISSUE TITLE
WINITNET.DLL error on Windows NT 3.51 

### ISSUE THREAD

**Issue by KylesDigitalLab** [jfchapman/VUPlayer#7]
I installed VUPlayer 2.49 on my Windows NT 3.51 VirtualBox VM. However, I get this error:
![image](https://user-images.githubusercontent.com/35104994/55687700-ffbd8b80-593d-11e9-8e3f-2122a5398fc4.png)

I have WINITNET.DLL in the System32 folder (C:\WINNT35\system32), and it's from my Office 97 install I have on this VM. since 97. I've been able to get VUPlayer working on NT 4.0 SP6 with Office XP and IE 6. 

I have SP5 on this VM.

**Comment by jfchapman** [comment]
If I'm honest, it's been many years since I used a version of Windows older than 2000, so I won't be able to resolve the issue on NT3.51. Interesting to know that it runs on NT4 though.
I tend to only run Windows 10 these days. I have a Windows 7 SP1 VM for testing, which is now the minimum supported system for the 'live' VUPlayer codebase.
